export const ticketStatus = [
    "In progress",
    "Waiting for customer",
    "Escalated to T2",
    "Escalated to RnD",
    "Escalated to CSM",
    "Waiting for RMA",
    "Pending for MW",
    "Ongoing",
    "Suspended",
    "Resolved",
    "Closed",
    "To do",
    "Moved to LIFT",
    "Pending for SW",
];
